config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'circles#index'
  get  '/circle_account' => 'pages#circle_account'
  get "circles/:id/favorites" => "circles#favorites"
  get "circles/:id/posts" => "circles#posts"

  devise_for :admin_users, controller: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :circles
  resources :circles do
    resources :favorites, only: [:create, :destroy]
  end

  resources :users
  resources :circle_posts

  # FIXME 下記を追加するとactive Storageの画像のリンクも含まれるため画像が表示されない
  # get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :circle_categories, dependent: :destroy
  has_many :circles, through: :circle_categories
end

app/models/circle.rb
class Circle < ApplicationRecord
  has_one :circle_time, dependent: :destroy
  accepts_nested_attributes_for :circle_time
  has_one :circle_image, dependent: :destroy
  has_one :image, through: :circle_image, class_name: 'Image', source: :image
  has_one :circle_account, dependent: :destroy

  has_many :circle_days, dependent: :destroy
  has_many :day_of_weeks, through: :circle_days
  has_many :favorites, dependent: :destroy
  has_many :circle_categories, dependent: :destroy
  has_many :categories, through: :circle_categories

  def favorited?(user)
    favorites.where(user: user).exists?
  end

  def upload_image(image)
    build_circle_image.build_image.image.attach(image)
  end

  def circle_account?(user)
    user && user.circle_account  = circle_account
  end
end

app/models/circle_account.rb
class CircleAccount < ApplicationRecord
  belongs_to :user
  belongs_to :circle
  has_many :circle_posts, dependent: :destroy
end

app/models/circle_category.rb
class CircleCategory < ApplicationRecord
  belongs_to :circle
  belongs_to :category
end

app/models/circle_day.rb
class CircleDay < ApplicationRecord
  belongs_to :circle
  belongs_to :day_of_week
end

app/models/circle_image.rb
class CircleImage < ApplicationRecord
  belongs_to :image, dependent: :destroy
  belongs_to :circle
end

app/models/circle_post.rb
class CirclePost < ApplicationRecord
  belongs_to :circle_account
  has_one :circle_post_image, dependent: :destroy
  has_one :image, through: :circle_post_image, class_name: 'Image', source: :image
  default_scope -> { order(created_at: :desc) }

  validates :circle_account_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  def upload_image(image)
    build_circle_post_image.build_image.image.attach(image)
  end
end

app/models/circle_post_image.rb
class CirclePostImage < ApplicationRecord
  belongs_to :image, dependent: :destroy
  belongs_to :circle_post
end

app/models/circle_time.rb
class CircleTime < ApplicationRecord
  belongs_to :circle
end

app/models/day_of_week.rb
class DayOfWeek < ApplicationRecord
  has_many :circle_days
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :circle
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :image
  has_one :circle_image, dependent: :destroy
  has_one :circle_post_image, dependent: :destroy

  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size: { less_than: 5.megabytes,
                            message: "should be less than 5MB" }

  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :favorites, dependent: :destroy
  has_one :circle_account, dependent: :destroy

  def twitter_link
    "https://twitter.com/#{self.twitter_id}"
  end

  def instagram_link
    "https://www.instagram.com/#{self.instagram_id}/"
  end

  def favorite(circle)
    favorites.create(circle: circle)
  end

  def unfavorite(circle)
    favorites.find_by(circle: circle).destroy
  end

  def favorite_of(circle)
    favorites.find_by(circle: circle)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_circle, only: [:create, :destroy]
  before_action :sign_in_required, only: [:create, :destroy]

  def create
    current_user.favorite(@circle)
    redirect_to @circle
  end
  
  def destroy
    current_user.unfavorite(@circle)
    redirect_to @circle
  end

  private
    def set_circle
      @circle = Circle.find(params[:circle_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user && user == current_user
  end

  def default_meta_tags
    {
      site: 'KURAKAN',
      title: '帝京大学のサークル紹介サイト',
      reverse: true,
      separator: '|',
      description: '帝京大学の部、同好会、愛好会の全てのサークルが掲載されているサイトです。また、3つの便利な機能があります。一つ目はどれくらいの人がそのサークルを気になっているのかが知ることができ、どんな人がどんなサークルを気になっているのかどんなサークルを気になっているのかを知ることができます。二つ目が気になっているサークルを気になっているサークルをお気に入り登録できます。三つ目がサークル関係者からのお知らせがタイムライン形式で流れてきます。',
      keywords: '帝京大学,サークル一覧,サークル,帝京,クラブ勧誘',
      canonical: request.original_url,
      noindex: ! Rails.env.production?,
      icon: [
        { href: image_url('kurakan.ico') },
        { href: image_url('kurakan.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'KURAKAN',
        title: '帝京大学のサークル紹介サイト',
        description: '帝京大学の部、同好会、愛好会の全てのサークルが掲載されているサイトです。また、3つの便利な機能があります。一つ目はどれくらいの人がそのサークルを気になっているのかが知ることができ、どんな人がどんなサークルを気になっているのかどんなサークルを気になっているのかを知ることができます。二つ目が気になっているサークルを気になっているサークルをお気に入り登録できます。三つ目がサークル関係者からのお知らせがタイムライン形式で流れてきます。', 
        type: 'website',
        url: request.original_url,
        image: image_url('kurakan_ogp.jpg'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@MOKUMOKUpro',
      }
    }
  end
end

app/helpers/circle_posts_helper.rb
module CirclePostsHelper
  def display_created_at(created_at)
    created_at&.strftime("%m月%d日 %I:%M")
  end
end

app/helpers/circles_helper.rb
module CirclesHelper
  def display_time(active_time)
    active_time&.strftime("%I:%M")
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flash_helper.rb
module FlashHelper

  def flash_class(level)
    case level
      when 'success' then 'bg-teal-100 border-teal-500 text-teal-900'
      when 'info' then 'bg-blue-100 border-blue-500 text-blue-900'
      when 'warning' then 'bg-yellow-100 border-yellow-500 text-yellow-900'
      when 'danger' then 'bg-red-100 border-red-500 text-red-900'
    end
  end
        
  def flash_status(status)
    case status
      when 'success' then content_tag :p, "Success", class: "font-bold"
      when 'info' then content_tag :p, "Info", class: "font-bold"
      when 'warning' then content_tag :p, "Warning", class: "font-bold"
      when 'danger' then content_tag :p, "Error", class: "font-bold"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name_exist?(user)
    user.name.present? ? user.name : '名無しさん'
  end
end

app/views/favorites/_favorite_button.html.erb
<span class="flex items-center">
  <%= render 'favorites/like_button', { circle: circle } %>
  <%= render 'favorites/favorite_count', { circle: circle } %>
</span>

app/views/favorites/_favorite_circle.html.erb
<li id="favorites-<%= favorite.id %>">
  <%= link_to circle_path(favorite.circle) do %>
    <div class="bg-white p-4 rounded-2xl border flex flex-row items-center justify-between">
      <%= link_to favorite.circle.name, favorite.circle, { class: "text-gray-900 text-lg title-font font-medium truncate mx-2" } %>
      <%= render 'favorites/like_button', { circle: favorite.circle } %> 
    </div>
  <% end %>
</li>

app/views/favorites/_favorite_count.html.erb
<%= link_to circle_favorites_path(circle) do %>
  <span class="text-gray-600 ml-2 text-lg"><%= circle.favorites.count %> いいね</span>
<% end %>

app/views/favorites/_favorite_user.html.erb
<li id="favorites-<%= favorite.id %>">
  <%= link_to user_path(favorite.user) do %>
    <div class="bg-white p-4 rounded-2xl border flex flex-row items-center justify-start">
      <%= link_to user_name_exist?(favorite.user), favorite.user, { class: "text-gray-900 text-lg title-font font-medium truncate mx-2" } %>
    </div>
  <% end %>
</li>

app/views/favorites/_like_button.html.erb
<% if circle.favorited?(current_user) %>
  <%= link_to circle_favorite_path(circle, current_user.favorite_of(circle)), method: :delete do %>
    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
      <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z" />
    </svg>
  <% end %>
  <% else %>
  <%= link_to circle_favorites_path(circle), method: :post do %>
    <svg class="h-8 w-8 text-black" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
    </svg>
  <% end %>
<% end %>