config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'circles#index'
  get  '/circle_account' => 'pages#circle_account'
  get "circles/:id/favorites" => "circles#favorites"
  get "circles/:id/posts" => "circles#posts"

  devise_for :admin_users, controller: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :circles
  resources :circles do
    resources :favorites, only: [:create, :destroy]
  end

  resources :users
  resources :circle_posts

  # FIXME 下記を追加するとactive Storageの画像のリンクも含まれるため画像が表示されない
  # get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/circle.rb
class Circle < ApplicationRecord
  has_one :circle_time, dependent: :destroy
  accepts_nested_attributes_for :circle_time
  has_one :circle_image, dependent: :destroy
  has_one :image, through: :circle_image, class_name: 'Image', source: :image
  has_one :circle_account, dependent: :destroy

  has_many :circle_days, dependent: :destroy
  has_many :day_of_weeks, through: :circle_days
  has_many :favorites, dependent: :destroy
  has_many :circle_categories, dependent: :destroy
  has_many :categories, through: :circle_categories

  def favorited?(user)
    favorites.where(user: user).exists?
  end

  def upload_image(image)
    build_circle_image.build_image.image.attach(image)
  end

  def circle_account?(user)
    user && user.circle_account  = circle_account
  end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  include ApplicationHelper
  before_action :set_circle, only: %i[ show edit update destroy favorites posts ]
  before_action :set_day_of_weeks, only: %i[ show edit new ]
  before_action :set_categories, only: %i[ index edit new ]
  before_action :authenticate_admin_user!, only: %i[ new create destroy ]
  before_action :correct_circle_account, only: %i[ edit update posts ]

  def index
    @circles = Circle.paginate(page: params[:page], per_page: 15)
    @circles = @circles.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    @circles = @categories.find(params[:category_id]).circles.paginate(page: params[:page], per_page: 15) if params[:category_id].present?
  end

  def show
  end

  def new
    @circle = Circle.new
    @circle.build_circle_time
  end

  def edit
  end

  def favorites
    @favorites = @circle.favorites
  end

  def posts
    @posts = @circle.circle_account.circle_posts.paginate(page: params[:page], per_page: 15)
  end

  def create
    @circle = Circle.new(circle_params)
    @circle.upload_image(params[:circle][:image])
    if @circle.save
      flash[:success] = "作成しました"
      redirect_to @circle
    else
      flash[:danger] = "作成に失敗しました"
      render 'new'
    end
  end


  def update
    @circle.upload_image(params[:circle][:image]) if params[:circle][:image].present?
    if @circle.update(circle_params)
      flash[:success] = "更新しました"
      redirect_to @circle
    else
      flash[:danger] = "更新に失敗しました"
      render 'edit'
    end
  end

  private
    def set_circle
      @circle = Circle.find(params[:id])
    end

    def set_day_of_weeks
      @day_of_weeks = DayOfWeek.all
    end

    def set_categories
      @categories = Category.all
    end

    def circle_params
      params.require(:circle).permit(:name, :description, :active_place, :number_of_people, :link, day_of_week_ids: [], circle_time_attributes: [:active_start_time, :active_end_time], category_ids: [])
    end

    def correct_circle_account
      circle = Circle.find(params[:id])
      redirect_to(circle_url) unless circle.circle_account?(current_user)
    end
end

app/helpers/circles_helper.rb
module CirclesHelper
  def display_time(active_time)
    active_time&.strftime("%I:%M")
  end
end

app/views/circles/_circle.html.erb
<div class="w-full xl:w-1/2 sm:p-4">
  <div class="bg-white p-4 sm:h-64 rounded-2xl shadow-lg flex flex-col sm:flex-row gap-5 select-none">
    <div class="h-52 sm:h-full sm:w-72 rounded-xl <%= 'bg-gray-200 animate-pulse' if !circle.image&.image&.attached? %>">
      <%= image_tag circle.image&.display_image, class: "w-full h-52 sm:h-full sm:w-72 rounded-xl object-cover object-center rounded" if circle.image&.image&.attached? %> 
    </div>
    <div class="flex flex-col flex-1 gap-5 sm:p-2">
      <div class="flex flex-1 flex-col gap-3">
        <div class="w-full h-14 rounded-2xl">
          <%= link_to circle.name, circle, { class: "text-gray-900 text-3xl title-font font-medium mb-1 line-clamp-1" } %>
        </div>
        <div class="<%= 'bg-gray-200 animate-pulse h-3' if circle.description.blank? %> w-full rounded-2xl">
          <p class="leading-relaxed mb-5 line-clamp-2"><%= circle.description %></p>
        </div>
      </div>
      <div class="mt-auto flex gap-3 items-center justify-between">
        <%= render 'favorites/favorite_button', { circle: circle } %> 
        <%= link_to 'more >', circle, { class: "text-blue-600 text-lg"} %>
      </div>
    </div>
  </div>
</div>

app/views/circles/edit.html.erb
<section class="container text-gray-600 body-font overflow-hidden">
  <div class="w-full mt-6 lg:mt-0 lg:pl-10 lg:py-6">
    <h2 class="text-gray-900 text-lg font-medium title-font">サークル編集</h2>

    <%= form_with(model: @circle, local: true, class: 'flex flex-col md:ml-auto w-full mt-10 md:mt-0 space-y-4') do |f| %>
      <div class="field">
        <%= f.label :name, "サークル名", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "サークル名", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :description, "サークル詳細", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_area :description, autocomplete: "サークル詳細", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :active_place, "活動場所", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_field :active_place, autocomplete: "活動場所", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <%= f.fields_for :circle_time, @circle.circle_time do |cf| %>
        <div class="flex space-x-4" >
          <div class="field w-full">
            <%= cf.label :active_start_time, "活動時間（始まり）", { class: 'leading-7 text-sm text-gray-600' } %><br />
            <%= cf.time_field :active_start_time, autocomplete: "off", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
          </div>

          <div class="field w-full">
            <%= cf.label :active_end_time, "活動時間（終わり）", { class: 'leading-7 text-sm text-gray-600' } %><br />
            <%= cf.time_field :active_end_time, autocomplete: "off", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
          </div>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :day_of_week_ids, "活動日", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.collection_check_boxes :day_of_week_ids, @day_of_weeks, :id, :day_name, include_hidden: false do |day_of_week| %>
          <%= day_of_week.label do %>
            <%= day_of_week.check_box %>
            <%= day_of_week.text %>
          <% end %>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :number_of_people, "人数", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.number_field :number_of_people, autocomplete: "1", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :link, "リンク", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_field :link, autocomplete: "リンク", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :category_ids, "カテゴリー", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.collection_check_boxes :category_ids, @categories, :id, :name, include_hidden: false do |category| %>
          <%= category.label do %>
            <%= category.check_box %>
            <%= category.text %>
          <% end %>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :image, "画像", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.file_field :image %>
      </div>

      <div class="actions">
        <%= f.submit "更新", { class: 'w-full text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg' } %>
      </div>
    <% end %>
  </div>
</section>

app/views/circles/favorites.html.erb
<section class="container text-gray-600 body-font overflow-hidden">
  <div class="mx-auto flex flex-wrap items-center justify-center">
    <% if @circle.favorites.any? %>
      <ol class="flex flex-col space-y-3 w-full md:w-1/2">
        <% @favorites.each do |favorite|%>
          <%= render 'favorites/favorite_user', { favorite: favorite } %>
        <% end %>
      </ol>
    <% end %>
  </div>
</section>

app/views/circles/index.html.erb
<section class="text-gray-600 body-font container">
  <div class="flex flex-wrap flex-col">
    <%= form_with url: circles_path, method: :get, local: true, html: {class: "w-full flex flex-row justify-end gap-5"} do |f| %>
      <%= f.text_field :search, placeholder: "名前検索", class: "rounded-lg border border-gray-300 w-full md:w-1/3 py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
      <%= f.submit '検索する',  { class: "flex-shrink-0 px-4 py-2 text-base font-semibold text-white bg-purple-600 rounded-lg shadow-md hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 focus:ring-offset-purple-200" } %>
    <% end %>
    <%= form_tag circles_path, method: :get, class: 'w-full flex flex-row flex-wrap mt-3 gap-2' do %>
      <div class="px-4 py-2  text-base rounded-full text-white bg-purple-600">
        <%= link_to "全て", circles_path %>
      </div>
      <% @categories.each do |category| %>
          <div class="px-4 py-2  text-base rounded-full text-white bg-purple-600">
            <%= link_to category.name, circles_path(category_id: category.id) %>
          </div>
      <% end %>
    <% end %>

    <div class="h-10 w-full"></div>
    <div class="w-full flex flex-wrap">
      <%= render @circles %>
    </div>
    <div class="mx-auto text-center my-4">
      <%= will_paginate %>
    </div>
  </div>
</section>

app/views/circles/new.html.erb
<section class="container text-gray-600 body-font overflow-hidden">
  <div class="w-full mt-6 lg:mt-0 lg:pl-10 lg:py-6">
    <h2 class="text-gray-900 text-lg font-medium title-font">サークル作成</h2>

    <%= form_with(model: @circle, local: true, class: 'flex flex-col md:ml-auto w-full mt-10 md:mt-0 space-y-4') do |f| %>
      <div class="field">
        <%= f.label :name, "サークル名", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "サークル名", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :description, "サークル詳細", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_area :description, autocomplete: "サークル詳細", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :active_place, "活動場所", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_field :active_place, autocomplete: "活動場所", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <%= f.fields_for :circle_time, @circle.circle_time do |cf| %>
        <div class="flex space-x-4">
          <div class="field w-full">
            <%= cf.label :active_start_time, "活動時間（始まり）", { class: 'leading-7 text-sm text-gray-600' } %><br />
            <%= cf.time_field :active_start_time, autocomplete: "off", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
          </div>

          <div class="field w-full">
            <%= cf.label :active_end_time, "活動時間（終わり）", { class: 'leading-7 text-sm text-gray-600' } %><br />
            <%= cf.time_field :active_end_time, autocomplete: "off", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
          </div>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :day_of_week_ids, "活動日", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.collection_check_boxes :day_of_week_ids, @day_of_weeks, :id, :day_name, include_hidden: false do |day_of_week| %>
          <%= day_of_week.label do %>
            <%= day_of_week.check_box %>
            <%= day_of_week.text %>
          <% end %>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :number_of_people, "人数", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.number_field :number_of_people, autocomplete: "1", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :link, "リンク", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.text_field :link, autocomplete: "リンク", class: 'w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out' %>
      </div>

      <div class="field">
        <%= f.label :category_ids, "カテゴリー", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.collection_check_boxes :category_ids, @categories, :id, :name, include_hidden: false do |category| %>
          <%= category.label do %>
            <%= category.check_box %>
            <%= category.text %>
          <% end %>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :image, "画像", { class: 'leading-7 text-sm text-gray-600' } %><br />
        <%= f.file_field :image %>
      </div>

      <div class="actions">
        <%= f.submit "作成", { class: 'w-full text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg' } %>
      </div>
    <% end %>
  </div>
</section>

app/views/circles/posts.html.erb
<section class="container text-gray-600 body-font">
  <div class="w-full mx-auto flex flex-col flex-wrap items-center justify-center">
    <% if @circle.circle_account&.circle_posts.any? %>
        <% @posts.each do |post|%>
          <%= render 'circle_posts/circle_post', { circle_post: post } %>
        <% end %>
      <div class="mx-auto text-center my-4">
        <%= will_paginate @posts %>
      </div>
    <% else %>
      <div class="text-xl">投稿はありません</div>
    <% end %>
  </div>
</section>

app/views/circles/show.html.erb
<section class="container text-gray-600 body-font overflow-hidden">
  <div class="mx-auto flex flex-wrap items-center">
    <div class="lg:w-1/2 w-full h-64 lg:h-full rounded-xl <%= 'lg:h-96 bg-gray-200 animate-pulse' if !@circle.image&.image&.attached? %>">
      <%= image_tag @circle.image&.display_image, class: "w-full h-64 md:h-full max-h-96 rounded-xl object-cover object-center rounded" if @circle.image&.image&.attached? %> 
    </div>
    <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
      <div class="flex max-w-xs">
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-1"><%= @circle.name %></h1>
        <% if @circle.circle_account?(current_user) %>
          <%= link_to edit_circle_path do %>
            <svg class="h-6 w-6 text-black" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z"/>
              <path d="M9 7 h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3" />
              <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" />
              <line x1="16" y1="5" x2="19" y2="8" />
            </svg> 
          <% end %>
        <% end %>
      </div>
      <div class="flex mb-4 mt-2">
        <%= render 'favorites/favorite_button', { circle: @circle } %> 
      </div>
      <p class="leading-relaxed mb-5"><%= @circle.description %></p>
      <div class="flex border-t border-gray-200 py-2">
        <span class="text-gray-500">活動場所</span>
        <span class="ml-auto text-gray-900"><%= @circle.active_place %></span>
      </div>
      <div class="flex border-t border-gray-200 py-2 justify-between">
        <span class="text-gray-500">活動日</span>
        <div>
          <% @day_of_weeks.each_with_index do |day_of_week, i| %>
            <span class="ml-1 text-gray-900 <%= 'py-1.5 px-2 rounded-full bg-blue-200 items-center justify-center' if @circle.day_of_weeks&.include?(day_of_week) %>"><%= day_of_week.day_name %></span>
          <% end %>
        </div>
      </div>
      <div class="flex border-t border-gray-200 py-2">
        <span class="text-gray-500">活動時間</span>
        <span class="ml-auto text-gray-900"><%= display_time(@circle.circle_time&.active_start_time) %> ~ <%= display_time(@circle.circle_time&.active_end_time) %></span>
      </div>
      <div class="flex border-t border-gray-200 py-2">
        <span class="text-gray-500">人数</span>
        <span class="ml-auto text-gray-900"><%= @circle.number_of_people %>人</span>
      </div>
      <div class="flex border-t border-b mb-6 border-gray-200 py-2">
        <span class="text-gray-500">リンク</span>
        <span class="ml-auto text-gray-900"><%= @circle.link %></span>
      </div>
    </div>
  </div>
</section>