config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'circles#index'
  get  '/circle_account' => 'pages#circle_account'
  get "circles/:id/favorites" => "circles#favorites"
  get "circles/:id/posts" => "circles#posts"

  devise_for :admin_users, controller: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :circles
  resources :circles do
    resources :favorites, only: [:create, :destroy]
  end

  resources :users
  resources :circle_posts

  # FIXME 下記を追加するとactive Storageの画像のリンクも含まれるため画像が表示されない
  # get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :circle_categories, dependent: :destroy
  has_many :circles, through: :circle_categories
end

app/models/circle.rb
class Circle < ApplicationRecord
  has_one :circle_time, dependent: :destroy
  accepts_nested_attributes_for :circle_time
  has_one :circle_image, dependent: :destroy
  has_one :image, through: :circle_image, class_name: 'Image', source: :image
  has_one :circle_account, dependent: :destroy

  has_many :circle_days, dependent: :destroy
  has_many :day_of_weeks, through: :circle_days
  has_many :favorites, dependent: :destroy
  has_many :circle_categories, dependent: :destroy
  has_many :categories, through: :circle_categories

  def favorited?(user)
    favorites.where(user: user).exists?
  end

  def upload_image(image)
    build_circle_image.build_image.image.attach(image)
  end

  def circle_account?(user)
    user && user.circle_account  = circle_account
  end
end

app/models/circle_account.rb
class CircleAccount < ApplicationRecord
  belongs_to :user
  belongs_to :circle
  has_many :circle_posts, dependent: :destroy
end

app/models/circle_category.rb
class CircleCategory < ApplicationRecord
  belongs_to :circle
  belongs_to :category
end

app/models/circle_day.rb
class CircleDay < ApplicationRecord
  belongs_to :circle
  belongs_to :day_of_week
end

app/models/circle_image.rb
class CircleImage < ApplicationRecord
  belongs_to :image, dependent: :destroy
  belongs_to :circle
end

app/models/circle_post.rb
class CirclePost < ApplicationRecord
  belongs_to :circle_account
  has_one :circle_post_image, dependent: :destroy
  has_one :image, through: :circle_post_image, class_name: 'Image', source: :image
  default_scope -> { order(created_at: :desc) }

  validates :circle_account_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  def upload_image(image)
    build_circle_post_image.build_image.image.attach(image)
  end
end

app/models/circle_post_image.rb
class CirclePostImage < ApplicationRecord
  belongs_to :image, dependent: :destroy
  belongs_to :circle_post
end

app/models/circle_time.rb
class CircleTime < ApplicationRecord
  belongs_to :circle
end

app/models/day_of_week.rb
class DayOfWeek < ApplicationRecord
  has_many :circle_days
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :circle
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :image
  has_one :circle_image, dependent: :destroy
  has_one :circle_post_image, dependent: :destroy

  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size: { less_than: 5.megabytes,
                            message: "should be less than 5MB" }

  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :favorites, dependent: :destroy
  has_one :circle_account, dependent: :destroy

  def twitter_link
    "https://twitter.com/#{self.twitter_id}"
  end

  def instagram_link
    "https://www.instagram.com/#{self.instagram_id}/"
  end

  def favorite(circle)
    favorites.create(circle: circle)
  end

  def unfavorite(circle)
    favorites.find_by(circle: circle).destroy
  end

  def favorite_of(circle)
    favorites.find_by(circle: circle)
  end
end

app/helpers/circles_helper.rb
module CirclesHelper
  def display_time(active_time)
    active_time&.strftime("%I:%M")
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/flash_helper.rb
module FlashHelper

  def flash_class(level)
    case level
      when 'success' then 'bg-teal-100 border-teal-500 text-teal-900'
      when 'info' then 'bg-blue-100 border-blue-500 text-blue-900'
      when 'warning' then 'bg-yellow-100 border-yellow-500 text-yellow-900'
      when 'danger' then 'bg-red-100 border-red-500 text-red-900'
    end
  end
        
  def flash_status(status)
    case status
      when 'success' then content_tag :p, "Success", class: "font-bold"
      when 'info' then content_tag :p, "Info", class: "font-bold"
      when 'warning' then content_tag :p, "Warning", class: "font-bold"
      when 'danger' then content_tag :p, "Error", class: "font-bold"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name_exist?(user)
    user.name.present? ? user.name : '名無しさん'
  end
end

app/views/layouts/_footer.html.erb
<footer class="text-gray-600 body-font">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:py-2 sm:mt-0 mt-4">© 2022 もくプロ —
      <a href="https://twitter.com/MOKUMOKUpro" class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">@MOKUMOKUpro</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <%= link_to 'サークルアカウント作成申請はこちら', 'https://forms.gle/PoSHVtkDaqxehigu5' %>
      <%= link_to 'https://twitter.com/MOKUMOKUpro', class: "ml-3 text-gray-500" do %>
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      <% end %>
      <%= link_to 'https://www.instagram.com/mokupro/', class: "ml-3 text-gray-500" do %>
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      <% end %>
    </span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="text-gray-600 body-font sticky top-0 bg-white">
  <div class="container mx-auto flex flex-wrap flex-col p-5 md:flex-row items-start justify-between">
    <div class="flex justify-between items-center w-full md:w-1/5">
      <%= link_to "KURAKAN", "/", { class: 'title-font font-medium text-gray-900 text-xl' } %>
      <% if user_signed_in? %>
        <button class="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block md:hidden outline-none focus:outline-none" type="button" onclick="isOpened(event)">
          <span class="block relative w-6 h-px rounded-sm bg-black"></span>
          <span class="block relative w-6 h-px rounded-sm bg-black mt-1"></span>
          <span class="block relative w-6 h-px rounded-sm bg-black mt-1"></span>
        </button>
      <% else %>
        <button class="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block md:hidden outline-none focus:outline-none" type="button" onclick="isOpened(event)">
          <span class="block relative w-6 h-px rounded-sm bg-black"></span>
          <span class="block relative w-6 h-px rounded-sm bg-black mt-1"></span>
          <span class="block relative w-6 h-px rounded-sm bg-black mt-1"></span>
        </button>
      <% end %>
    </div>
    <nav id="nav" class="md:ml-auto flex flex-wrap flex-col-reverse md:flex-row items-start md:items-center text-base hidden md:flex">
      <%= link_to 'タイムライン', circle_posts_path, class: "md:ml-3 mt-2 lg:mt-0" %>
      <% if user_signed_in? %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "md:ml-2 mt-2 lg:mt-0" %>
        <% if current_user.circle_account %>
          <%= link_to circle_account_path, class: "md:ml-2 mt-2 lg:mt-0 hover:text-gray-900" do %>
            <svg class="h-8 w-8 text-black" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z"/>
              <line x1="15" y1="5" x2="15" y2="7" />
              <line x1="15" y1="11" x2="15" y2="13" />
              <line x1="15" y1="17" x2="15" y2="19" />
              <path d="M5 5h14a2 2 0 0 1 2 2v3a2 2 0 0 0 0 4v3a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-3a2 2 0 0 0 0 -4v-3a2 2 0 0 1 2 -2" />
            </svg>
          <% end %>
        <% end %>
        <%= link_to user_path(current_user), class: "md:ml-2 mt-2 lg:mt-0 hover:text-gray-900" do %>
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
          </svg>
        <% end %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path, class: "md:ml-3 mt-2 lg:mt-0" %>
        <%= link_to 'ログイン', new_user_session_path, class: "md:ml-3 mt-2 lg:mt-0" %>
      <% end %>
      <%= link_to 'adminログアウト', destroy_admin_user_session_path, method: :delete, class: "md:ml-2 mt-2 lg:mt-0" if admin_user_signed_in? %>
    </nav>
  </div>
</header>

<script>
  function isOpened(event){
    const nav = document.getElementById("nav");
    if (nav.classList.contains('hidden')) {
      nav.classList.remove("hidden")
    } else {
      nav.classList.add("hidden")
    }
  }
</script>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/rails_default" %>
    <%= display_meta_tags (default_meta_tags) %>
  </head>

  <body class="h-screen flex flex-col justify-between">
    <%= render "layouts/header" %>
    <main class="flex-grow container mx-auto px-5 py-10 md:py-24 flex flex-col items-center justify-center">
      <%= render "shared/flash" %> 
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/circle_account.html.erb
<section class="container text-gray-600 body-font overflow-hidden">
  <div class="mx-auto flex flex-col flex-wrap items-center justify-center gap-3">
    <div class="w-full md:w-1/2 text-center bg-white p-4 rounded-2xl border">
      <%= link_to "投稿作成", new_circle_post_path, { class: "text-gray-900 text-lg title-font font-medium truncate mx-2" } %>
    </div>
    <div class="w-full md:w-1/2 text-center bg-white p-4 rounded-2xl border">
      <%= link_to "投稿一覧", "circles/#{@circle_account.circle.id}/posts", { class: "text-gray-900 text-lg title-font font-medium truncate mx-2" } %>
    </div>
    <div class="w-full md:w-1/2 text-center bg-white p-4 rounded-2xl border">
      <%= link_to "サークル情報", circle_path(@circle_account.circle), { class: "text-gray-900 text-lg title-font font-medium truncate mx-2" } %>
    </div>
    <div class="w-full md:w-1/2 text-center bg-white p-4 rounded-2xl border">
      <%= link_to "いいね一覧", circle_favorites_path(@circle_account.circle), { class: "text-gray-900 text-lg title-font font-medium truncate mx-2" } %>
    </div>
  </div>
</section>

app/views/pages/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#index</h1>
  <p>Find me in app/views/pages/index.html.erb</p>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> border-t-4 rounded-b px-4 py-3 shadow-md flex mb-2 items-center" role="alert">
    <%= flash_status(key) %>
    <p class="text-sm"><%= value %></p>
    <button type="button" onclick="closeAlert(event)">&times;</button>
  </div>
  <script>
    function closeAlert(event){
      let element = event.target;
      while(element.nodeName !== "BUTTON"){
        element = element.parentNode;
      }
      element.parentNode.parentNode.removeChild(element.parentNode);
    }
  </script>
<% end %>